# Permalinks
permalink:           pretty

# Setup
title:               Raj Bhowmick - Beginner Data Science Blog
tagline:             Blogging my journey as a Data Science Padawan
url:                 https://questiegit.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              'Raj Bhowmick'
  url:               https://github.com/questiegit
  email:             

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/questiegit/questiegit.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
